version: '3.8'

services:
  # Banco de Dados (PostgreSQL)
  postgres-db:
    image: postgres:15-alpine
    container_name: topseguidores-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sua_senha_forte}
      POSTGRES_DB: ${POSTGRES_DB:-topseguidores}
    ports:
      - "5436:5432"
    volumes:
      - topseguidores-data:/var/lib/postgresql/data

  # Aplicação Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: topseguidores-app
    restart: always
    ports:
      - "3010:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin_user}:${POSTGRES_PASSWORD:-sua_senha_forte}@postgres-db:5432/${POSTGRES_DB:-topseguidores}?schema=public
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - RAPID_API_KEY=${RAPID_API_KEY}
      - NEXT_PUBLIC_RAPIDAPI_KEY=${RAPID_API_KEY} # Usa a mesma chave para o client-side
      - PUSHINPAY_TOKEN=${PUSHINPAY_TOKEN}
      - PUSHINPAY_WEBHOOK_TOKEN=${PUSHINPAY_WEBHOOK_TOKEN}
      - PIX_PAYER_DOCUMENT=${PIX_PAYER_DOCUMENT}
      - PERFECT_PANEL_URL=${PERFECT_PANEL_URL}
      - PERFECT_PANEL_KEY=${PERFECT_PANEL_KEY}
      - FB_PIXEL_ID=${FB_PIXEL_ID}
      - FB_API_TOKEN=${FB_API_TOKEN}
    depends_on:
      - postgres-db

volumes:
  topseguidores-data:
    driver: local
