services:
  postgres:
    image: postgres:15
    container_name: socialfornece-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialfornece
    ports:
      - "5436:5432"
    volumes:
      - postgres-data-social:/var/lib/postgresql/data

volumes:
  postgres-data-social:
