version: '3.8'

services:
  # Banco de Dados (PostgreSQL)
  postgres-db:
    image: postgres:15-alpine
    container_name: topseguidores-db
    restart: always
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: sua_senha_forte # Recomenda-se trocar em produção
      POSTGRES_DB: topseguidores
    ports:
      - "5436:5432" # Porta externa 5436 para evitar conflito com padrão 5432
    volumes:
      - topseguidores-data:/var/lib/postgresql/data

  # Aplicação Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: topseguidores-app
    restart: always
    ports:
      - "3010:3000" # Mapeia a porta 3010 para a aplicação
    environment:
      - DATABASE_URL=postgresql://admin_user:sua_senha_forte@postgres-db:5432/topseguidores?schema=public
      - NEXTAUTH_SECRET=sua_secret_aqui
      - NEXTAUTH_URL=http://localhost:3010
      # Adicione outras variáveis do .env conforme necessário
    depends_on:
      - postgres-db

volumes:
  topseguidores-data:
    driver: local
